name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_OIDC_ROLE_ARN: ${{ vars.AWS_OIDC_ROLE_ARN }}
  AWS_ECR_NAME: ${{ vars.AWS_ECR_NAME }}
  AWS_SECRET_NAME: ${{ vars.AWS_SECRET_NAME }}
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get ECR Repository URI
        id: get-ecr-uri
        run: |
          ECR_URI=$(aws ecr describe-repositories --region $AWS_REGION --query "repositories[?repositoryName=='${{ env.AWS_ECR_NAME }}'].repositoryUri" --output text)
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

      - name: Build and Tag Docker Image
        run: |
          docker build -t $ECR_URI:latest .

      - name: Push Docker Image to ECR
        run: |
          docker push $ECR_URI:latest

      - name: Update AWS Secrets Manager with Discord Secrets
        run: |
          aws secretsmanager update-secret --region $AWS_REGION \
            --secret-id $AWS_SECRET_NAME \
            --secret-string '{"DISCORD_BOT_TOKEN": "'${DISCORD_BOT_TOKEN}'", "DISCORD_CLIENT_SECRET": "'${DISCORD_CLIENT_SECRET}'"}'
